FROM python:3.12.7-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    zsh \
    nodejs \
    openssh-client \ 
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --shell /usr/bin/zsh appuser

WORKDIR /app

COPY ../requirements/prod.txt ./requirements/prod.txt
RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements/prod.txt

RUN mkdir -p /home/appuser/.ssh
COPY .ssh/ /home/appuser/.ssh/
RUN chown -R appuser:appuser /home/appuser/.ssh
RUN chmod 700 /home/appuser/.ssh
RUN chmod 600 /home/appuser/.ssh/*

COPY .. .

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir /usr/local/bin

USER appuser

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
RUN echo 'eval "$(starship init zsh)"' >> ~/.zshrc


RUN mkdir -p /home/appuser/.config && \
    echo '[character]' >> /home/appuser/.config/starship.toml && \
    echo 'success_symbol = "[➜](bold green)"' >> /home/appuser/.config/starship.toml && \
    echo 'error_symbol = "[✖︎](bold red)"' >> /home/appuser/.config/starship.toml && \
    echo '[nodejs]' >> /home/appuser/.config/starship.toml && \
    echo 'disabled = true' >> /home/appuser/.config/starship.toml && \
    echo '[python]' >> /home/appuser/.config/starship.toml && \
    echo 'disabled = true' >> /home/appuser/.config/starship.toml

RUN git config --global user.name "" && \
    git config --global user.email ""

WORKDIR /app
